name: 'elementary_observability'
version: '1.0.0'
config-version: 2
profile: 'elementary_snowflake'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  elementary_observability:
      +materialized: view


vars:
  elementary:
    schemas_monitoring_configuration: ELEMENTARY_MONITORING.TEST_ELEMENTARY_OBSERVABILITY.MONITORING_SCHEMAS_CONFIGURATION
    tables_monitoring_configuration: ELEMENTARY_MONITORING.TEST_ELEMENTARY_OBSERVABILITY.MONITORING_TABLES_CONFIGURATION
    columns_monitoring_configuration: ELEMENTARY_MONITORING.TEST_ELEMENTARY_OBSERVABILITY.MONITORING_COLUMNS_CONFIGURATION