name: "elementary"
version: "0.5.3"

require-dbt-version: [ ">=1.0.0", "<2.0.0" ]

config-version: 2
profile: "elementary"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "dbt_modules"

on-run-start:
  - "{{ elementary.create_elementary_tests_schema() if flags.WHICH in ['test', 'build'] }}"
on-run-end:
  - "{{ elementary.upload_dbt_invocation() if not elementary.get_config_var('disable_autoupload_dbt_invocation') }}"
  - "{{ elementary.upload_dbt_artifacts() if not elementary.get_config_var('disable_autoupload_dbt_artifacts') }}"
  - "{{ elementary.upload_run_results(results) if not elementary.get_config_var('disable_run_results') }}"
  - "{{ elementary.handle_tests_results(results) if flags.WHICH in ['test', 'build'] }}"
