name: "elementary"
version: "0.1.1"

require-dbt-version: [">=1.0.0", "<2.0.0"]

config-version: 2
profile: "elementary"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "dbt_modules"

on-run-start: "{{ elementary.on_run_start() }}"
on-run-end: "{{ elementary.on_run_end() }}"


models:
  elementary:
    edr:
      data_monitoring:
        +enabled: "{{ target.type != 'databricks' | as_bool() }}"
      metadata_store:
        +enabled: "{{ target.type != 'databricks' | as_bool() }}"
      system:
        +enabled: "{{ target.type != 'databricks' | as_bool() }}"