name: 'elementary'
version: '0.1.1'

require-dbt-version: [">=0.20.0", "<1.1.0"]

config-version: 2
profile: 'elementary'

source-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "dbt_modules"

on-run-end: "{{ merge_test_results() }}"





