version: 2

sources:
  - name: 'elementary_dbt_artifacts'
    database: '{{ var("elementary_metadata_database", target.database) }}'
    schema: '{{ var("elementary_metadata_schema", target.schema) }}'
    tables:
      - name: 'dbt_run_results'
        columns:
          - name: 'model_execution_id'
          - name: 'unique_id'
          - name: 'invocation_id'
          - name: 'generated_at'
          - name: 'name'
          - name: 'status'
          - name: 'resource_type'
          - name: 'execution_time'
          - name: 'execute_started_at'
          - name: 'execute_completed_at'
          - name: 'compile_started_at'
          - name: 'compile_completed_at'
          - name: 'rows_affected'
          - name: 'full_refresh'
      - name: 'dbt_models'
        columns:
          - name: 'unique_id'
          - name: 'alias'
          - name: 'checksum'
          - name: 'materialization'
          - name: 'tags'
          - name: 'meta'
          - name: 'database_name'
          - name: 'schema_name'
          - name: 'depends_on_macros'
          - name: 'depends_on_nodes'
          - name: 'description'
          - name: 'name'
          - name: 'package_name'
          - name: 'original_path'
          - name: 'path'
          - name: 'generated_at'
      - name: 'dbt_tests'
        columns:
          - name: 'unique_id'
          - name: 'database_name'
          - name: 'schema_name'
          - name: 'name'
          - name: 'short_name'
          - name: 'alias'
          - name: 'test_column_name'
          - name: 'severity'
          - name: 'warn_if'
          - name: 'error_if'
          - name: 'tags'
          - name: 'meta'
          - name: 'depends_on_macros'
          - name: 'depends_on_nodes'
          - name: 'description'
          - name: 'package_name'
          - name: 'original_path'
          - name: 'path'
          - name: 'generated_at'
      - name: 'dbt_sources'
        columns:
          - name: 'unique_id'
          - name: 'database_name'
          - name: 'schema_name'
          - name: 'source_name'
          - name: 'name'
          - name: 'identifier'
          - name: 'loaded_at_field'
          - name: 'freshness_warn_after'
          - name: 'freshness_error_after'
          - name: 'freshness_filter'
          - name: 'relation_name'
          - name: 'tags'
          - name: 'meta'
          - name: 'package_name'
          - name: 'original_path'
          - name: 'path'
          - name: 'source_description'
          - name: 'description'
          - name: 'generated_at'
      - name: 'dbt_exposures'
        columns:
          - name: 'unique_id'
          - name: 'name'
          - name: 'maturity'
          - name: 'type'
          - name: 'owner_email'
          - name: 'owner_name'
          - name: 'url'
          - name: 'depends_on_macros'
          - name: 'depends_on_nodes'
          - name: 'description'
          - name: 'tags'
          - name: 'meta'
          - name: 'package_name'
          - name: 'original_path'
          - name: 'path'
          - name: 'generated_at'
      - name: 'dbt_metrics'
        columns:
          - name: 'unique_id'
          - name: 'name'
          - name: 'label'
          - name: 'model'
          - name: 'type'
          - name: 'sql'
          - name: 'timestamp'
          - name: 'filters'
          - name: 'time_grains'
          - name: 'dimensions'
          - name: 'depends_on_macros'
          - name: 'depends_on_nodes'
          - name: 'description'
          - name: 'tags'
          - name: 'meta'
          - name: 'package_name'
          - name: 'original_path'
          - name: 'path'
          - name: 'generated_at'
