name: 'elementary_integration_tests'
version: '1.0.0'
config-version: 2
profile: 'elementary_tests'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "dbt_modules"

on-run-start:
  - "{{ clear_tests() }}"

on-run-end:
  - "{{ elementary.merge_test_results() }}" # in prod this is called from within the package, it's called here in tests so we can run validations on the final tables
  - "{{ tests_validation() }}"
  - "{{ elementary.upload_dbt_artifacts(results) }}"

vars:
  days_back: 30
  elementary_debug_logs: true
  dbt_artifacts_schema: 'test_artifacts'

models:
  elementary:
    +schema: elementary

