version: 2

sources:
  - name: integration_test
    schema: test

    tables:
      - name: groups
        - columns:
            - name: group_a
              meta:
                data_type: text
            - name: group_b
              meta:
                data_type: text

      - name: matches
      - name: stats_players
      - name: stats_team
        - columns:
          - name: crosses
            meta:
              data_type: number
          - name: interceptions
              data_type: number
