version: 2

models:
  - name: string_column_anomalies
    config:
      edr:
        timestamp_column: 'updated_at'
        monitored: true
    tests:
      - elementary.table_anomalies:
          tags: ['elementary']
          table_tests:
            - row_count
    columns:
      - name: min_length
        tests:
          - elementary.column_anomalies:
              tags: ['elementary_c']
              column_tests:
                - min_length
                - max_length