version: 2

models:
  - name: string_column_anomalies
    config:
      edr:
        monitored: true
        timestamp_column: 'updated_at'
        columns_monitored: true
  - name: numeric_column_anomalies
    config:
      edr:
        monitored: true
        timestamp_column: 'updated_at'
        columns_monitored: true
  - name: any_type_column_anomalies
    config:
      edr:
        monitored: true
        timestamp_column: 'updated_at'
        columns_monitored: true