version: 2

models:
  - name: string_column_anomalies
    config:
      edr:
        timestamp_column: 'updated_at'
        monitored: true
    tests:
      - elementary.table_anomalies:
          tags: ['elementary_c']
          table_tests:
            - row_count
    columns:
      - name: min_length
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']
              column_tests:
                - min_length
                - max_length
      - name: max_length
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']
      - name: average_length
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']
              column_tests:
                - average_length
                - null_count
      - name: missing_count
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']
      - name: missing_percent
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']
      - name: updated_at
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']

  - name: numeric_column_anomalies
    config:
      edr:
        timestamp_column: 'updated_at'
        monitored: true
    tests:
      - elementary.table_anomalies:
          tags: ['elementary']
    columns:
      - name: min
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']
              column_tests:
                - min
          - elementary.column_anomalies:
              tags: ['elementary']
              column_tests:
                - max
          - elementary.column_anomalies:
              tags: ['elementary']
              column_tests:
                - average
      - name: max
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']
              column_tests:
                - min
          - elementary.column_anomalies:
              tags: ['elementary']
              column_tests:
                - max
          - elementary.column_anomalies:
              tags: ['elementary']
              column_tests:
                - average
      - name: average
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']
              column_tests:
                - min
          - elementary.column_anomalies:
              tags: ['elementary']
              column_tests:
                - max
          - elementary.column_anomalies:
              tags: ['elementary']
              column_tests:
                - average
      - name: zero_count
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']
      - name: zero_percent
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']
      - name: updated_at
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']
      - name: variance
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']
      - name: standard_deviation
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']

sources:
  - name: 'snowflake_account_usage'
    schema: 'accunt_usage'
    database: 'snowflake'
    tables:
      - name: query_history
        identifier: query_history
        tests:
          - elementary.table_anomalies
        columns:
          - name: query_type
            tests:
              - elementary.column_anomalies:
                  tags: ['elementary']
          - name: seesion_id
            tests:
              - elementary.column_anomalies:
                  tags: ['elementary']
          - name: user_name
            tests:
              - elementary.column_anomalies:
                  tags: ['elementary']
          - name: role_name
            tests:
              - elementary.column_anomalies:
                  tags: ['elementary']
          - name: warehouse_id
            tests:
              - elementary.column_anomalies:
                  tags: ['elementary']
          - name: total_elapsed_time
            tests:
              - elementary.column_anomalies:
                  tags: ['elementary']
          - name: query_id
            tests:
              - elementary.column_anomalies:
                  tags: ['elementary']
      - name: metering_history
        identifier: metering_history
        tests:
          - elementary.table_anomalies
        columns:
          - name: entity_id
            tests:
              - elementary.column_anomalies:
                  tags: ['elementary']
          - name: CREDITS_USED_COMPUTE
            tests:
              - elementary.column_anomalies:
                  tags: ['elementary']
          - name: CREDITS_USED_CLOUD_SERVICES
            tests:
              - elementary.column_anomalies:
                  tags: ['elementary']
          - name: name
            tests:
              - elementary.column_anomalies:
                  tags: ['elementary']
          - name: service_type
            tests:
              - elementary.column_anomalies:
                  tags: ['elementary']