version: 2

models:
  - name: u_any_Type_column_anomalies #the capital T and the prefix 'u' here are intendend to test how the code handles it
    description: >
      This is a very weird description
      with breaklines
      and comma,
      and even a string like this 'wow'. You know, these $##$34#@#!^ can also be helpful
      WDYT?
    config:
      elementary:
        timestamp_column: 'updated_at'
    tests:
      - elementary.table_anomalies:
          tags: ['table_anomalies']
          table_anomalies:
            - row_count
      - elementary.all_columns_anomalies:
          tags: ['all_columns_anomalies']

  - name: string_column_anomalies
    config:
      elementary:
        timestamp_column: "updated_at"
    tests:
      - elementary.table_anomalies:
          tags: ['table_anomalies']
          table_anomalies:
            - freshness
      - elementary.all_columns_anomalies:
          tags: ['all_columns_anomalies']
      - elementary.schema_changes:
          tags: ['schema_changes']
    columns:
      - name: "min_length"
        tests:
          - elementary.column_anomalies:
              tags: ['specific_column_anomalies']
              column_anomalies:
                - min_length
                - max_length
                - missing_count
      - name: max_length
        tests:
          - elementary.column_anomalies:
              tags: ['column_anomalies']
      - name: average_length
        tests:
          - elementary.column_anomalies:
              tags: ['specific_column_anomalies']
              column_anomalies:
                - average_length
                - null_count
      - name: missing_count
        tests:
          - elementary.column_anomalies:
              tags: ['column_anomalies']
      - name: missing_percent
        tests:
          - elementary.column_anomalies:
              tags: ['column_anomalies']
      - name: updated_at
        tests:
          - elementary.column_anomalies:
              tags: ['column_anomalies']

  - name: numeric_column_anomalies
    config:
      elementary:
        timestamp_column: 'updated_at'
    tests:
      - elementary.table_anomalies:
          tags: ['table_anomalies']
      - elementary.schema_changes:
          tags: ['schema_changes']
    columns:
      - name: min
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']
              column_anomalies:
                - min
          - elementary.column_anomalies:
              tags: ['elementary']
              column_anomalies:
                - max
          - elementary.column_anomalies:
              tags: ['elementary']
              column_anomalies:
                - average
      - name: max
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']
              column_anomalies:
                - min
          - elementary.column_anomalies:
              tags: ['elementary']
              column_anomalies:
                - max
          - elementary.column_anomalies:
              tags: ['elementary']
              column_anomalies:
                - average
      - name: average
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']
              column_anomalies:
                - min
          - elementary.column_anomalies:
              tags: ['elementary']
              column_anomalies:
                - max
          - elementary.column_anomalies:
              tags: ['elementary']
              column_anomalies:
                - average
      - name: zero_count
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']
      - name: zero_percent
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']
      - name: updated_at
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']
      - name: variance
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']
      - name: standard_deviation
        tests:
          - elementary.column_anomalies:
              tags: ['elementary']

sources:
  - name: training
    schema: "{{ target.schema }}"
    tables:
      - name: any_type_column_anomalies_training
        tests:
          - elementary.table_anomalies:
              tags: ['table_anomalies']
      - name: string_column_anomalies_training
        meta:
          elementary:
            timestamp_column: 'date'
        tests:
          - elementary.table_anomalies:
              tags: ['table_anomalies']
  - name: validation
    schema: "{{ target.schema }}"
    tables:
      - name: any_type_column_anomalies_validation
        tests:
          - elementary.all_columns_anomalies:
              tags: ['elementary_source']
  - name: test_data
    schema: "{{ target.schema }}"
    tables:
      - name: groups
        tests:
          - elementary.schema_changes:
              tags: ['schema_changes']
      - name: stats_players
        tests:
          - elementary.schema_changes:
              tags: ['schema_changes']
      - name: stats_team
        tests:
          - elementary.schema_changes:
              tags: ['schema_changes']