name: Generate seed data for all platforms
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  TESTS_DIR: ${{ github.workspace }}/dbt-data-reliability/integration_tests

jobs:
  generate-data:
    strategy:
      fail-fast: false
      matrix:
        warehouse-type: [ snowflake, bigquery, redshift, databricks ]
    steps:
      - name: Write dbt profiles
        env:
          CI_PROFILES_YML: ${{ secrets.CI_PROFILES_YML }}
        run: |
          mkdir -p ~/.dbt
          UNDERSCORED_REF_NAME=$(echo "${{ env.BRANCH_NAME }}" | sed "s/-/_/g")
          echo "$CI_PROFILES_YML" | base64 -d | sed "s/<SCHEMA_NAME>/dbt_$UNDERSCORED_REF_NAME/g" > ~/.dbt/profiles.yml

      - name: Checkout Elementary
        uses: actions/checkout@v3
        with:
          repository: elementary-data/elementary
          path: elementary

      - name: Checkout dbt package
        uses: actions/checkout@v3
        with:
          path: dbt-data-reliability

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7.5'

      - name: Install dbt
        run: pip install "dbt-core" "dbt-${{ matrix.warehouse-type }}"

      - name: Install Elementary
        run: pip install "./elementary[${{ matrix.warehouse-type }}]"

      - name: Run E2E tests
        working-directory: ${{ env.TESTS_DIR }}
        run: |
          dbt deps
          python run_e2e_tests.py --generate-only
