name: Test warehouse platform
on:
  workflow_dispatch:
    inputs:
      warehouse-type:
        type: choice
        required: true
        options:
          - snowflake
          - bigquery
          - redshift
          - databricks
      elementary-ref:
        type: string
        required: false
      dbt-data-reliability-ref:
        type: string
        required: false

  workflow_call:
    inputs:
      warehouse-type:
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: tests-${{ inputs.warehouse-type }}
    steps:
      - name: Write dbt profiles
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.CI_PROFILES_YML }}" | base64 -d > ~/.dbt/profiles.yml

      - name: Checkout Elementary
        uses: actions/checkout@v3
        with:
          repository: elementary-data/elementary
          path: elementary
          ref: ${{ inputs.elementary-ref }}

      - name: Checkout dbt package
        uses: actions/checkout@v3
        with:
          path: dbt-data-reliability
          ref: ${{ inputs.dbt-data-reliability-ref }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Elementary
        run: pip install './elementary[${{ inputs.warehouse-type }}]'

      - name: Run E2E tests
        run: |
          dbt deps --project-dir ./dbt-data-reliability/integration_tests
          python ./dbt-data-reliability/integration_tests/run_e2e_tests.py -t ${{ inputs.warehouse-type }}
