name: Test all warehouse platforms
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    dbt-version:
      type: string
      required: false
      description: dbt's version to test with

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        warehouse-type: [ postgres, snowflake, bigquery, redshift, databricks ]
    uses: ./.github/workflows/test-warehouse.yml
    with:
      warehouse-type: ${{ matrix.warehouse-type }}
      dbt-version: ${{ github.event_name != 'workflow_dispatch' && '1.0.2' || inputs.dbt-version }}
    secrets: inherit
